### ISSUE TITLE
failed to run demo_o3d_server.py

### ISSUE THREAD

**Issue by roachsinai** [jinfagang/alfred#25]
After run `pip install alfred-py`, run script `demo_o3d_server.py` in examples dir get error:

```
❯❯❯ py .\demo_o3d_server.py
Traceback (most recent call last):
  File ".\demo_o3d_server.py", line 18, in <module>
    main()
  File ".\demo_o3d_server.py", line 8, in main
    cfg = get_default_visconfig()
  File "C:\Users\xq\miniconda3\envs\nn\lib\site-packages\alfred\vis\mesh3d\o3d_visconfig.py", line 87, in get_default_visconfig
    cfg = Config.load(
  File "C:\Users\xq\miniconda3\envs\nn\lib\site-packages\alfred\utils\base_config.py", line 21, in load
    cfg.merge_from_file(filename)
  File "C:\Users\xq\miniconda3\envs\nn\lib\site-packages\yacs\config.py", line 211, in merge_from_file
    with open(cfg_filename, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\xq\\miniconda3\\envs\\nn\\lib\\site-packages\\alfred\\vis\\mesh3d\\default_viscfg.yml'
```

Then found there is no `assets` and `default_viscfg.yml` under site-packages:

```
❯❯❯ ls -l
total 88
drwxrwxr-x    2 xq       xq            4096 Feb 27 15:32 __pycache__
-rw-rw-r--    1 xq       xq           35379 Feb 27 15:32 o3d_visconfig.py
-rw-rw-r--    1 xq       xq            8368 Feb 27 15:32 o3dsocket.py
-rw-rw-r--    1 xq       xq           15428 Feb 27 15:32 o3dwrapper.py
-rw-rw-r--    1 xq       xq            5552 Feb 27 15:32 skelmodel.py
-rw-rw-r--    1 xq       xq            9290 Feb 27 15:32 utils.py
```

So should I copy those files to site-packages as function `get_default_visconfig` do not allow arguments. Or other good suggestions?

Thanks!

**Comment by jinfagang** [comment]
@roachsinai what's your usage scenarios for o3d_server? this API is not very stable (not intended for common use), it was developed used inside my project. Might have some bugs.

**Comment by roachsinai** [comment]
Thanks for your reply! Just wanna know the data format send to o3d_server, so try to run the example.

**Comment by roachsinai** [comment]
Thanks, but need more time to read the code.
